[project]
name = "auto-bindings"
version = "0.1.0"
description = "Generate Zig bindings for RocksDB's C API"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "codegen",
    "libclang>=18.1.1",
]

[tool.uv.workspace]
members = [
    "codegen",
]

[tool.uv.sources]
codegen = { workspace = true, editable = true }
